name: tumbleweed-rmt-server 2

on:

  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight

jobs:

  build:
    runs-on: ubuntu-latest


    steps:
    
      - name: Install ansible-bender
        run: pip3 install ansible-bender
        
      
        
  
        
      
