name: tumbleweed-rmt-server

on:

  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Buildah
        uses: redhat-actions/buildah-build@v2
        with:
          id: build-image
          # The base image to use to create a new container image
          base-image: registry.opensuse.org/opensuse/tumbleweed:latest
          image: ${{ github.workflow }}
          tags: >-
            ${{ github.sha }}
            ${{ github.run_number }}
            latest
           
      #Check if image is build
      - name: Check images created
        run: buildah images
        
      - name: test
        run: echo "${{ github.run_number }}"
        
      - name: test 2
        run: echo "${{ github.sha }}"
        
     "
        
          
